---
- name: garantindo os pacotes principais
  package:
    name:
      - docker-ce
      - nginx
      - python-pip


- name: Instalando docker-py
  pip:
    name: docker-py

- name: Inicializando servicos
  service:
    name: "{{ item }}"
    state: started
  with_items:
    - nginx
    - docker 
