---
- name: Instalar apache no debian
  package:
   name:
    - apache2
  when: ansible_os_family == "Debian"

- name: Instalar apache no CentOS
  package:
   name:
    - httpd
  when: ansible_os_family == "RedHat"

- name: Iniciar servico debian
  service:
   name: 'apache2'
   state: started
  when: ansible_os_family == "Debian"

- name: Iniciar servico centos
  service:
   name: 'httpd'
   state: started
  when: ansible_os_family == "RedHat"
